#!/bin/bash 

#!/bin/bash

# This script takes two path parameters and calls another script with these absolute paths.

# Check if exactly two arguments are given
if [ "$#" -ne 2 ]; then
    echo "Usage: $0 <path1> <path2>"
    exit 1
fi

# Convert input paths to absolute paths
absolute_path1=$(realpath "$1")
absolute_path2=$(realpath "$2")

# Get the directory where this script is located
script_dir=$(dirname "$(readlink -f "$0")")

# Path to the script to be called, assumed to be in the same directory as this script
script_to_call="$script_dir/src/main_cmd.py"

# Check if the script to be called exists and is executable
if [ ! -f "$script_to_call" ]; then
    echo "Error: The script '$script_to_call' does not exist or is not executable."
    exit 2
fi

# Call the script with the absolute paths
python3 "$script_to_call" --smt2 "$absolute_path1" --config "$absolute_path2"
